### ISSUE TITLE
support urlfetch or urllib2 so it can be used in app engine

### ISSUE THREAD

**Issue by ubaldo** [kliment/pymill#1]
curl isnt' supported in app engine

**Comment by kliment** [comment]
I don't think either of those can actually validate an SSL certificate, so it will not be secure, but I can look into it.

**Comment by ubaldo** [comment]
I'm already using paymill with urlfetch fom google app engine

**Comment by kliment** [comment]
Cool. Does it actually validate SSL certificates on app engine? Can you share your code. I'll be happy to support either backend.

**Comment by ubaldo** [comment]
Yes u could send you the code tomorrow, i took ideas/code from stripe python library. Check it out, it's mature

**Comment by kliment** [comment]
Excellent. I'll see what I can use to improve mine. Have you considered 
putting yours on github?

**Comment by ubaldo** [comment]
Well no, its not very refined. I basicallly took was was there in github from paymill and replace some parts with ideas from stripe, namely the urlfetch and error handling to some extent because json error information that comes back from paymill isnt very detailed.

**Comment by kliment** [comment]
Switched backend to Requests which is reported to work on App Engine
