### ISSUE TITLE
Fill meta-data and register as package on Pypi

### ISSUE THREAD

**Issue by mekza** [kliment/pymill#12]
Hi,

This block is mandatory in setup.py.

```
author = "",
author_email = "",
maintainer = "",
maintainer_email = "",
```

then you can use `python setup.py register`

**Comment by Natim** [comment]
:+1: 

It could be really nice to have the last release directly doing `pip install pymill`

**Comment by superalex** [comment]
I registered as package on Pypi -> https://pypi.python.org/pypi/pymill/ and now you can use `pip install pymill`
If you have a pypi user I can make you the owner of the package ;)

**Comment by Natim** [comment]
Thank you very much for that it is really great !

**Comment by Natim** [comment]
Try to add kliment it may be is pypi username.

**Comment by superalex** [comment]
pypi says "user doesn't exist"

**Comment by kliment** [comment]
It does now. :)

**Comment by superalex** [comment]
Perfect, now you are the owner too! :+1:
