### ISSUE TITLE
Issue with currency and offers

### ISSUE THREAD

**Issue by epicbagel** [kliment/pymill#5]
> > > p.newoffer(amount = 29, interval = 'month', currency = 'usd', name = 'test')
> > > {u'error': {u'field': u'currency', u'messages': {u'required': u'Parameter is mandatory'}}}
> > > p.newoffer(amount = 29, interval = 'month', currency = 'eur', name = 'test')
> > > {u'error': {u'field': u'currency', u'messages': {u'required': u'Parameter is mandatory'}}}

Can't seem to create offers via the API?

**Comment by kliment** [comment]
I believe I just fixed this. Please try it now.

**Comment by epicbagel** [comment]
Fixed. Thanks.
